$background = rgb(19101C)
$foreground = rgb(BFB6C2)
$color0 = rgb(4C4336)
$color1 = rgb(482E51)
$color2 = rgb(4E355A)
$color3 = rgb(523753)
$color4 = rgb(B99064)
$color5 = rgb(A2A4DA)
$color6 = rgb(ECBC6C)
$color7 = rgb(9B8EA0)
$color8 = rgb(6C6370)
$color9 = rgb(482E51)
$color10 = rgb(4E355A)
$color11 = rgb(523753)
$color12 = rgb(B99064)
$color13 = rgb(A2A4DA)
$color14 = rgb(ECBC6C)
$color15 = rgb(9B8EA0)
