$background = rgb(070713)
$foreground = rgb(ADACB9)
$color0 = rgb(453D35)
$color1 = rgb(141337)
$color2 = rgb(20173C)
$color3 = rgb(231F3D)
$color4 = rgb(DB5189)
$color5 = rgb(A78976)
$color6 = rgb(FFD09C)
$color7 = rgb(818092)
$color8 = rgb(5A5A67)
$color9 = rgb(141337)
$color10 = rgb(20173C)
$color11 = rgb(231F3D)
$color12 = rgb(DB5189)
$color13 = rgb(A78976)
$color14 = rgb(FFD09C)
$color15 = rgb(818092)
