$wallpaper = Pictures/Wallpapers/incognito.jpg

$background = rgba(11140eff)

$error = rgba(ffb4abff)

$error_container = rgba(93000aff)

$inverse_on_surface = rgba(2e312aff)

$inverse_primary = rgba(466730ff)

$inverse_surface = rgba(e1e4d9ff)

$on_background = rgba(e1e4d9ff)

$on_error = rgba(690005ff)

$on_error_container = rgba(ffdad6ff)

$on_primary = rgba(193705ff)

$on_primary_container = rgba(c7eea9ff)

$on_primary_fixed = rgba(0a2100ff)

$on_primary_fixed_variant = rgba(2f4f1bff)

$on_secondary = rgba(283420ff)

$on_secondary_container = rgba(d9e7caff)

$on_secondary_fixed = rgba(141e0cff)

$on_secondary_fixed_variant = rgba(3e4a35ff)

$on_surface = rgba(e1e4d9ff)

$on_surface_variant = rgba(c4c8bbff)

$on_tertiary = rgba(003737ff)

$on_tertiary_container = rgba(bbecebff)

$on_tertiary_fixed = rgba(002020ff)

$on_tertiary_fixed_variant = rgba(1e4e4eff)

$outline = rgba(8e9286ff)

$outline_variant = rgba(43483eff)

$primary = rgba(acd28fff)

$primary_container = rgba(2f4f1bff)

$primary_fixed = rgba(c7eea9ff)

$primary_fixed_dim = rgba(acd28fff)

$scrim = rgba(000000ff)

$secondary = rgba(bdcbafff)

$secondary_container = rgba(3e4a35ff)

$secondary_fixed = rgba(d9e7caff)

$secondary_fixed_dim = rgba(bdcbafff)

$shadow = rgba(000000ff)

$source_color = rgba(77846bff)

$surface = rgba(11140eff)

$surface_bright = rgba(373a33ff)

$surface_container = rgba(1d211aff)

$surface_container_high = rgba(282b24ff)

$surface_container_highest = rgba(33362fff)

$surface_container_low = rgba(191d16ff)

$surface_container_lowest = rgba(0c0f09ff)

$surface_dim = rgba(11140eff)

$surface_tint = rgba(acd28fff)

$surface_variant = rgba(43483eff)

$tertiary = rgba(a0cfceff)

$tertiary_container = rgba(1e4e4eff)

$tertiary_fixed = rgba(bbecebff)

$tertiary_fixed_dim = rgba(a0cfceff)

